services:
  - type: web
    name: restapay-v2
    env: static
    buildCommand: npm install --no-audit --no-fund --loglevel verbose && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false