import {useMemo,useState} from 'react'
import {Banknote,ChevronDown,ChevronRight,CreditCard,Pencil,Plus,ReceiptText,Search,Trash2,WalletCards} from 'lucide-react'
import DateToolbar from '../components/DateToolbar'
import DetailDrawer from '../components/DetailDrawer'
import Modal from '../components/Modal'
import useCrudCollection from '../hooks/useCrudCollection'
import {useFeedback} from '../components/AppFeedback'
import {useAppData} from '../hooks/useAppData'
import useGlobalDateRange, { inDateRange } from '../hooks/useGlobalDateRange'
import { dedupeVendorOptions, normalizeVendorName } from '../lib/vendorCleanup'
import { reloadLiveCollection } from '../data/liveDataStore' 

const alpha=(a,b)=>String(a||'').localeCompare(String(b||''),undefined,{sensitivity:'base',numeric:true});const defaultTypes=['Accounting & Professional Fees','Advertising & Marketing','Alcohol License / Liquor License','Alcohol Purchase','Bank Charges','Business License','Cleaning','Credit Card / Processing Fees','Employee Benefits','Equipment','Fire / Safety Permit','Food Purchase','Food Service Permit','Health Permit','Insurance','Interest / Finance Charges','Maintenance','Marketing','Music / Entertainment License','Office Supplies','Other','Other Licenses & Permits','Payroll / Employee Wages','Payroll Tax','Pest Control','Professional Services','Property Tax','Rent','Rent / Lease','Repairs & Maintenance','Restaurant Supplies','Sales Tax','Security','Service Charges','Smallwares','Software / Technology','Supplies','Telephone / Internet','Uniforms & Linen','Utilities','Vehicle / Delivery','Waste / Garbage','Workers Compensation'].sort(alpha)
const blank=()=>({date:new Date().toISOString().slice(0,10),type:'Utilities',vendor:'',vendor_id:null,notes:'',amount:'',method:'Cash',check_number:'',recurring:false,status:'Paid'})

export default function Expenses(){
 const [rows,crud]=useCrudCollection('restapay-expenses',[]);const [vendors,vendorCrud]=useCrudCollection('restapay-vendors',[]);const vendorOptions=useMemo(()=>dedupeVendorOptions(vendors),[vendors]);const [types,setTypes]=useState(()=>{try{return (JSON.parse(localStorage.getItem('restapay-expense-types')||'null')||defaultTypes).slice().sort(alpha)}catch{return defaultTypes}});const {notify}=useFeedback();const {metrics}=useAppData()
 const [query,setQuery]=useState(''),[method,setMethod]=useState('All Methods'),[drawer,setDrawer]=useState(null),[modal,setModal]=useState(false),[edit,setEdit]=useState(null),[form,setForm]=useState(blank),[selectedIds,setSelectedIds]=useState([])
 const { range }=useGlobalDateRange()
 const scopedRows=useMemo(()=>(Array.isArray(rows)?rows:[]).filter(r=>inDateRange(r,range,['expense_date','date'])),[rows,range])
 const filtered=useMemo(()=>scopedRows.filter(r=>(!query||Object.values(r||{}).join(' ').toLowerCase().includes(query.toLowerCase()))&&(method==='All Methods'||(r.method||r.payment_type)===method)).sort((a,b)=>String(a.date||a.expense_date||'').localeCompare(String(b.date||b.expense_date||''))),[scopedRows,query,method])
 const open=(r=null)=>{setEdit(r?.id||null);setForm(r?{...r}:blank());setModal(true)}
 const addType=()=>{const value=prompt('Add expense type')?.trim();if(!value)return;const existing=types.find(type=>String(type).trim().toLowerCase()===value.toLowerCase());if(existing){setForm(f=>({...f,type:existing}));return notify('Existing expense type selected.')}const next=[...types,value].sort(alpha);setTypes(next);localStorage.setItem('restapay-expense-types',JSON.stringify(next));setForm(f=>({...f,type:value}));notify('Expense type added.')}
 const addVendor=async()=>{const name=prompt('Add vendor name')?.trim();if(!name)return;const existing=vendors.find(v=>normalizeVendorName(v.name)===normalizeVendorName(name));if(existing){setForm(f=>({...f,vendor:existing.name,vendor_id:existing.id}));return notify('Existing vendor selected.')}try{const vendorId=crypto.randomUUID?.()||`vendor-${Date.now()}`;await vendorCrud.add({id:vendorId,name,category:'Other',vendor_type:'Operating Expense',expense_type:form.type,is_active:true});await reloadLiveCollection('restapay-vendors').catch(()=>{});setForm(f=>({...f,vendor:name,vendor_id:vendorId}));notify('Vendor added to Supabase.')}catch(error){notify(error?.message||'Vendor could not be added.','error')}}
 const save=async()=>{if(!form.vendor||!form.amount)return notify('Vendor and amount are required.','error');const normalized={...form,amount:Number(form.amount)||0,check_number:form.check_number||'',payment_type:form.method,expense_date:form.date};try{if(edit)await crud.update(edit,normalized);else await crud.add(normalized);notify(edit?'Expense updated.':'Expense added.');setModal(false)}catch(error){notify(error?.message||'Expense could not be saved.','error')}}
 const del=async r=>{if(!confirm(`Delete ${r.type} expense?`))return;try{await crud.remove(r.id);setSelectedIds(ids=>ids.filter(id=>id!==r.id));notify('Expense deleted.')}catch(error){notify(error?.message||'Expense could not be deleted.','error')}}
 const visibleIds=filtered.map(r=>r.id).filter(Boolean);const allVisibleSelected=visibleIds.length>0&&visibleIds.every(id=>selectedIds.includes(id));const toggle=id=>setSelectedIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);const toggleAll=()=>setSelectedIds(ids=>allVisibleSelected?ids.filter(id=>!visibleIds.includes(id)):[...new Set([...ids,...visibleIds])]);const bulkDelete=async()=>{const count=selectedIds.length;if(!count||!confirm(`Delete ${count} selected expense${count===1?'':'s'}?`))return;try{await Promise.all(selectedIds.map(id=>crud.remove(id)));setSelectedIds([]);notify(`${count} expense${count===1?'':'s'} deleted.`)}catch(error){notify(error?.message||'Selected expenses could not be deleted.','error')}}
 const total=scopedRows.reduce((s,r)=>s+Number(r.amount||0),0);const cards=[['Total Expenses',total,'Current period','blue',ReceiptText],['Cash Expenses',scopedRows.filter(r=>(r.method||r.payment_type)==='Cash').reduce((s,r)=>s+Number(r.amount||0),0),'Paid in cash','green',Banknote],['Check & ACH',scopedRows.filter(r=>['Check','ACH'].includes(r.method||r.payment_type)).reduce((s,r)=>s+Number(r.amount||0),0),'Bank payments','purple',WalletCards],['Credit Expenses',scopedRows.filter(r=>(r.method||r.payment_type)==='Credit').reduce((s,r)=>s+Number(r.amount||0),0),'Card purchases','orange',CreditCard]]
 return <div className="records-page"><DateToolbar/>
  <section className="records-kpi-grid">{cards.map(([t,v,m,tone,Icon])=><button key={t} className={`records-kpi tone-${tone}`} onClick={()=>setDrawer(t)}><span className="records-kpi-icon"><Icon size={22}/></span><span className="records-kpi-copy"><strong>{t}</strong><b>${v.toLocaleString(undefined,{minimumFractionDigits:2})}</b><small>{m}</small></span><ChevronRight size={18}/></button>)}</section>
  <section className="records-workspace card-surface"><header className="records-header"><div><h2>Expenses</h2><p>Record operating expenses, vendors, payment methods and recurring charges</p></div><div className="records-header-actions">{selectedIds.length>0&&<button className="secondary-action danger-action" onClick={bulkDelete}><Trash2 size={16}/>Delete Selected ({selectedIds.length})</button>}<button className="primary-button" onClick={()=>open()}><Plus size={17}/>Add Expense</button></div></header>
   <div className="records-filterbar"><label className="records-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search expense or vendor..."/></label><label className="records-select"><select value={method} onChange={e=>setMethod(e.target.value)}><option>All Methods</option><option>ACH</option><option>Cash</option><option>Check</option><option>Credit</option><option>Other</option></select><ChevronDown size={14}/></label></div>
   <div className="records-table-wrap"><table className="records-table aligned-table"><thead><tr><th className="select-column"><input type="checkbox" aria-label="Select all visible expenses" checked={allVisibleSelected} onChange={toggleAll}/></th><th>Date</th><th>Expense Type</th><th>Vendor</th><th>Notes</th><th>Amount</th><th>Method</th><th>Actions</th></tr></thead><tbody>{filtered.length?filtered.map(r=><tr key={r.id} className={selectedIds.includes(r.id)?'row-selected':''}><td className="select-column"><input type="checkbox" aria-label={`Select ${r.type} expense`} checked={selectedIds.includes(r.id)} onChange={()=>toggle(r.id)}/></td><td>{r.date||r.expense_date}</td><td>{r.type}</td><td>{r.vendor}</td><td>{r.notes}</td><td className="numeric">${Number(r.amount).toLocaleString(undefined,{minimumFractionDigits:2})}</td><td>{r.method||r.payment_type}</td><td><div className="row-actions"><button onClick={()=>setDrawer({title:r.type,rows:[r]})}><ReceiptText size={15}/></button><button onClick={()=>open(r)}><Pencil size={15}/></button><button className="danger" onClick={()=>del(r)}><Trash2 size={15}/></button></div></td></tr>):<tr><td colSpan="8" className="empty-table-cell">No expenses recorded</td></tr>}</tbody></table></div>
  </section>
  <Modal open={modal} title={edit?'Edit Expense':'Add Expense'} subtitle="Enter an operating expense" onClose={()=>setModal(false)} footer={<><button className="secondary-action" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button" onClick={save}>Save Expense</button></>}><div className="form-grid"><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Expense Type<div className="vendor-select-row"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select><button type="button" className="inline-add-button" onClick={addType}><Plus size={15}/></button></div></label><label>Vendor<div className="vendor-select-row"><select value={form.vendor} onChange={e=>{const v=vendorOptions.find(x=>x.name===e.target.value);setForm({...form,vendor:e.target.value,vendor_id:v?.id||null})}}><option value="">Select vendor</option>{vendorOptions.filter(v=>v.is_active!==false).map(v=><option key={v.id} value={v.name}>{v.name}</option>)}</select><button type="button" className="inline-add-button" onClick={addVendor}><Plus size={15}/></button></div></label><label>Payment Method<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option>Cash</option><option>Check</option><option>ACH</option><option>Credit</option><option>Other</option></select></label><label>Amount<input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Check / Reference<input value={form.check_number||''} onChange={e=>setForm({...form,check_number:e.target.value})}/></label><label>Status<select value={form.status||'Paid'} onChange={e=>setForm({...form,status:e.target.value})}><option>Paid</option><option>Pending</option></select></label><label className="checkbox-field"><input type="checkbox" checked={Boolean(form.recurring)} onChange={e=>setForm({...form,recurring:e.target.checked})}/>Recurring expense</label><label className="form-span-2">Description / Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div></Modal>
  <DetailDrawer title={typeof drawer==='string'?drawer:drawer?.title} entries={drawer?.rows} onClose={()=>setDrawer(null)}/>
 </div>
}
