import {useMemo,useRef,useState} from 'react'
import * as XLSX from 'xlsx'
import {ChevronDown,ChevronRight,FileInput,Filter,Pencil,Plus,Search,Sparkles,Trash2} from 'lucide-react'
import Modal from '../components/Modal'
import DetailDrawer from '../components/DetailDrawer'
import useCrudCollection from '../hooks/useCrudCollection'
import {useFeedback} from '../components/AppFeedback'
import {calculateInvoice, normalizeInvoice} from '../core/engines/InvoiceEngine.js'
import {useAppData} from '../hooks/useAppData'
import {isSupabaseReady,supabase} from '../lib/supabase.js'

const today=()=>new Date().toISOString().slice(0,10)
const emptyLine=()=>({id:crypto.randomUUID?.()||`line-${Date.now()}`,item_number:'',description:'',category:'Food',quantity:1,package_size:'',unit_price:'',line_total:''})
const blank=()=>({date:today(),due_date:'',vendor:'',vendor_id:null,number:'',category:'Food',payment_type:'Check',check_number:'',status:'Due',tax:'',discount:'',notes:'',source_file:'',lines:[emptyLine()]})
const categories=['Food','Meat','Seafood','Produce','Dairy','Dry Goods','Frozen','Beer','Wine','Liquor','Margaritas','Cocktails & Shots','Supplies','Maintenance','Utilities','Other']

export default function Invoices(){
 const [rows,crud]=useCrudCollection('restapay-invoices',[]);const {vendors}=useAppData();const {notify}=useFeedback()
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All Categories'),[status,setStatus]=useState('All Status'),[modal,setModal]=useState(false),[ai,setAi]=useState(false),[edit,setEdit]=useState(null),[form,setForm]=useState(blank),[drawer,setDrawer]=useState(null),[aiDraft,setAiDraft]=useState(null);const fileRef=useRef(null)
 const filtered=useMemo(()=>rows.filter(r=>(!query||Object.values(r).join(' ').toLowerCase().includes(query.toLowerCase()))&&(category==='All Categories'||r.category===category)&&(status==='All Status'||r.status===status)),[rows,query,category,status])
 const vendorNames=useMemo(()=>[...new Set([...(vendors||[]).map(v=>v.name),...rows.map(r=>r.vendor)].filter(Boolean))].sort(),[vendors,rows])
 const open=(r=null)=>{setEdit(r?.id||null);setForm(r?normalizeInvoice(r):blank());setModal(true)}
 const updateLine=(id,field,value)=>setForm(f=>({...f,lines:f.lines.map(line=>{if(line.id!==id)return line;const next={...line,[field]:value};if(['quantity','unit_price'].includes(field)){next.line_total=((Number(next.quantity)||0)*(Number(next.unit_price)||0)).toFixed(2)}return next})}))
 const removeLine=id=>setForm(f=>({...f,lines:f.lines.length===1?[emptyLine()]:f.lines.filter(line=>line.id!==id)}))
 const totals=useMemo(()=>calculateInvoice(form.lines||[],form.tax,form.discount),[form.lines,form.tax,form.discount])
 const save=()=>{if(!form.number||!form.vendor)return notify('Vendor and invoice number are required.','error');const normalized=normalizeInvoice({...form,...totals});edit?crud.update(edit,normalized):crud.add(normalized);notify(edit?'Invoice updated.':'Invoice saved.');setModal(false)}
 const del=r=>confirm(`Delete invoice ${r.number}?`)&&(crud.remove(r.id),notify('Invoice deleted.'))
 const total=rows.reduce((s,r)=>s+Number(r.total??r.amount??0),0),due=rows.filter(r=>r.status==='Due').reduce((s,r)=>s+Number(r.total??r.amount??0),0)
 const cards=[['Invoice Total',total,'All invoices','blue'],['Food Invoices',rows.filter(r=>/food|meat|seafood|produce|dairy|dry|frozen/i.test(r.category||'')).length,'Food purchasing','green'],['Alcohol Invoices',rows.filter(r=>/alcohol|beer|wine|liquor|margarita|cocktail/i.test(r.category||'')).length,'Beer, wine and liquor','orange'],['Open Balance',due,'Due invoices','purple']]
 const parseFile=async file=>{try{const lower=file.name.toLowerCase();if(/\.(csv|xlsx|xls)$/.test(lower)){const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array'});const sheet=wb.Sheets[wb.SheetNames[0]];const json=XLSX.utils.sheet_to_json(sheet,{defval:''});const lines=json.map((row,index)=>({id:`ai-${Date.now()}-${index}`,item_number:row['Item #']||row.Item||row.SKU||row['Product Number']||'',description:row.Description||row.ItemDescription||row.Product||row.Name||'',category:row.Category||'Food',quantity:Number(row.Quantity||row.Qty||row.Shipped||1)||1,package_size:row.Size||row.Pack||row['Package Size']||'',unit_price:Number(row['Unit Price']||row.Price||row.Cost||0)||0,line_total:Number(row.Total||row.Amount||row.Extension||row['Extended Price']||0)||0})).filter(x=>x.description||x.line_total);const draft=blank();draft.source_file=file.name;draft.number=`AI-${Date.now().toString().slice(-6)}`;draft.vendor='Spreadsheet Review';draft.lines=lines.length?lines:[emptyLine()];const calc=calculateInvoice(draft.lines,0,0);setAiDraft({...draft,...calc});notify(`${file.name} parsed. Review the draft before saving.`);return}if(!isSupabaseReady)throw new Error('Supabase is not configured for secure Gemini extraction.');notify('Extracting invoice securely with Gemini...');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));const {data,error}=await supabase.functions.invoke('gemini-invoice',{body:{fileName:file.name,mimeType:file.type,data:btoa(binary)}});if(error)throw error;if(!data?.ok)throw new Error(data?.message||'Gemini extraction failed.');const lines=(data.lineItems||[]).map((line,index)=>({id:`ai-${Date.now()}-${index}`,item_number:line.item_number||'',description:line.description||'',brand:line.brand||'',category:line.category||data.category||'Other',quantity:Number(line.qty||1)||1,package_size:line.package_size||'',pack_count:Number(line.pack_count||0)||0,unit_size_value:Number(line.unit_size_value||0)||0,unit_size_unit:line.unit_size_unit||'',unit_price:Number(line.unit_price||0)||0,line_total:Number(line.total||0)||0}));const draft={...blank(),source_file:file.name,vendor:data.vendor_name||'AI Review',number:data.invoice_number||`AI-${Date.now().toString().slice(-6)}`,date:data.invoice_date||today(),category:data.category||'Other',tax:Number(data.tax||0),discount:Number(data.discount||0),lines:lines.length?lines:[emptyLine()]};const calc=calculateInvoice(draft.lines,draft.tax,draft.discount);setAiDraft({...draft,...calc,total:Number(data.total||calc.total)});notify('Gemini extraction completed. Review every field before saving.')}catch(error){notify(error?.message||`Could not parse ${file.name}.`,'error');setAiDraft({...blank(),source_file:file.name,number:`AI-${Date.now().toString().slice(-6)}`})}}
 const acceptAi=()=>{setForm(aiDraft);setEdit(null);setAi(false);setAiDraft(null);setModal(true)}
 return <div className="records-page">
  <section className="records-kpi-grid">{cards.map(([t,v,m,tone])=><button key={t} className={`records-kpi tone-${tone}`} onClick={()=>setDrawer(t)}><span className="records-kpi-icon"><FileInput size={22}/></span><span className="records-kpi-copy"><strong>{t}</strong><b>{['Invoice Total','Open Balance'].includes(t)?`$${Number(v).toLocaleString(undefined,{minimumFractionDigits:2})}`:v}</b><small>{m}</small></span><ChevronRight size={18}/></button>)}</section>
  <section className="records-workspace card-surface"><header className="records-header"><div><h2>Invoices</h2><p>Manual entry, smart upload, line items, vendor matching and payment status</p></div><div className="records-actions"><button className="secondary-action" onClick={()=>setAi(true)}><Sparkles size={17}/>Smart AI Upload</button><button className="primary-button" onClick={()=>open()}><Plus size={17}/>Manual Invoice</button></div></header>
   <div className="records-filterbar"><label className="records-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search invoices..."/></label><label className="records-select"><Filter size={16}/><select value={category} onChange={e=>setCategory(e.target.value)}><option>All Categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><label className="records-select"><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Paid</option><option>Due</option></select><ChevronDown size={14}/></label></div>
   <div className="records-table-wrap"><table className="records-table aligned-table"><thead><tr><th>Date</th><th>Vendor</th><th>Invoice #</th><th>Category</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.length?filtered.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.vendor}</td><td>{r.number}</td><td>{r.category}</td><td className="numeric">${Number(r.total??r.amount??0).toLocaleString(undefined,{minimumFractionDigits:2})}</td><td><button className={`status-badge status-${String(r.status).toLowerCase()}`} onClick={()=>crud.update(r.id,{status:r.status==='Paid'?'Due':'Paid'})}>{r.status}</button></td><td><div className="row-actions"><button onClick={()=>setDrawer({title:`Invoice ${r.number}`,rows:r.lines||[]})}><FileInput size={15}/></button><button onClick={()=>open(r)}><Pencil size={15}/></button><button className="danger" onClick={()=>del(r)}><Trash2 size={15}/></button></div></td></tr>):<tr><td colSpan="7" className="empty-table-cell">No invoices recorded</td></tr>}</tbody></table></div>
  </section>
  <Modal open={modal} title={edit?'Edit Invoice':'Manual Invoice Entry'} subtitle="Enter invoice header, payment details and line items" onClose={()=>setModal(false)} size="lg" footer={<><button className="secondary-action" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button" onClick={save}>Save Invoice</button></>}>
   <div className="form-grid"><label>Vendor<input list="invoice-vendors" value={form.vendor} onChange={e=>setForm({...form,vendor:e.target.value})}/><datalist id="invoice-vendors">{vendorNames.map(x=><option key={x} value={x}/>)}</datalist></label><label>Invoice Number<input value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></label><label>Invoice Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Due Date<input type="date" value={form.due_date||''} onChange={e=>setForm({...form,due_date:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Payment Type<select value={form.payment_type} onChange={e=>setForm({...form,payment_type:e.target.value})}><option>Cash</option><option>Check</option><option>ACH</option><option>Credit</option><option>Other</option></select></label><label>Check / Reference<input value={form.check_number||''} onChange={e=>setForm({...form,check_number:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Due</option><option>Paid</option></select></label></div>
   <div className="invoice-line-editor"><div className="invoice-line-heading"><div><h3>Invoice Line Items</h3><p>Line items feed food/alcohol cost, vendor comparison and price history.</p></div><button className="secondary-action" type="button" onClick={()=>setForm(f=>({...f,lines:[...f.lines,emptyLine()]}))}><Plus size={15}/>Add Line</button></div>
    <div className="invoice-line-grid invoice-line-header"><span>Item / Description</span><span>Category</span><span>Qty</span><span>Pack / Size</span><span>Unit Cost</span><span>Line Total</span><span></span></div>
    {form.lines.map(line=><div className="invoice-line-grid" key={line.id}><input value={line.description} onChange={e=>updateLine(line.id,'description',e.target.value)} placeholder="Product description"/><select value={line.category} onChange={e=>updateLine(line.id,'category',e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select><input type="number" min="0" step="0.01" value={line.quantity} onChange={e=>updateLine(line.id,'quantity',e.target.value)}/><input value={line.package_size} onChange={e=>updateLine(line.id,'package_size',e.target.value)} placeholder="2/10 LB"/><input type="number" min="0" step="0.01" value={line.unit_price} onChange={e=>updateLine(line.id,'unit_price',e.target.value)}/><input type="number" min="0" step="0.01" value={line.line_total} onChange={e=>updateLine(line.id,'line_total',e.target.value)}/><button className="icon-danger-button" type="button" onClick={()=>removeLine(line.id)}><Trash2 size={15}/></button></div>)}
   </div>
   <div className="invoice-totals"><label>Tax<input type="number" value={form.tax||''} onChange={e=>setForm({...form,tax:e.target.value})}/></label><label>Discount<input type="number" value={form.discount||''} onChange={e=>setForm({...form,discount:e.target.value})}/></label><div><span>Subtotal</span><strong>${totals.subtotal.toFixed(2)}</strong></div><div><span>Total</span><strong>${totals.total.toFixed(2)}</strong></div></div><label className="modal-full-field">Notes<textarea value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
  </Modal>
  <Modal open={ai} title="Smart AI Invoice Upload" subtitle="Choose a PDF, image, CSV, or Excel invoice" onClose={()=>{setAi(false);setAiDraft(null)}} size="lg" footer={aiDraft?<><button className="secondary-action" onClick={()=>{setAi(false);setAiDraft(null)}}>Cancel</button><button className="primary-button" onClick={acceptAi}>Review Draft Invoice</button></>:<button className="secondary-action" onClick={()=>setAi(false)}>Cancel</button>}><label className="upload-dropzone"><Sparkles size={28}/><strong>Select invoice file</strong><small>CSV/XLSX files parse locally. PDF and image files use the secure Gemini Edge Function.</small><input ref={fileRef} type="file" accept=".pdf,.png,.jpg,.jpeg,.csv,.xlsx,.xls" onChange={e=>e.target.files?.[0]&&parseFile(e.target.files[0])}/></label>{aiDraft&&<div className="ai-review-summary"><div><small>File</small><strong>{aiDraft.source_file}</strong></div><div><small>Lines detected</small><strong>{aiDraft.lines.length}</strong></div><div><small>Draft total</small><strong>${Number(aiDraft.total||0).toFixed(2)}</strong></div></div>}</Modal>
  <DetailDrawer title={typeof drawer==='string'?drawer:drawer?.title} entries={drawer?.rows} onClose={()=>setDrawer(null)}/>
 </div>
}
