import React,{useMemo,useState} from 'react'
import * as XLSX from 'xlsx'
import { Icon } from '../components/Icons'
import DateControls from '../components/DateControls'
import PayrollDailyGrid from '../components/PayrollDailyGrid'
import PayrollWeekBuilder from '../components/PayrollWeekBuilder'
import { createId } from '../lib/localStore'
import { detectToastLaborPeriod,laborImportDiagnostics,parseToastLaborRows } from '../engine/ToastLaborEngine'
import { groupPayrollByEmployee,originalTips,payrollEntryKey,payrollTotal,roundPayroll } from '../engine/PayrollEngine'
const iso=d=>d.toISOString().slice(0,10)
const today=()=>iso(new Date())
const monthStart=()=>iso(new Date(new Date().getFullYear(),new Date().getMonth(),1))
const money=v=>roundPayroll(v).toFixed(2)
const normalize=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'')
const displayName=value=>{const raw=String(value||'').trim();if(!raw.includes(','))return raw;const [last,first]=raw.split(',').map(x=>x.trim());return [first,last].filter(Boolean).join(' ')}
function presetRange(key){const now=new Date();if(key==='today')return[iso(now),iso(now)];if(key==='thisMonth')return[monthStart(),iso(now)];if(key==='lastWeek'){const end=new Date(now);end.setDate(now.getDate()-now.getDay());const start=new Date(end);start.setDate(end.getDate()-6);return[iso(start),iso(end)]}if(key==='lastMonth'){return[iso(new Date(now.getFullYear(),now.getMonth()-1,1)),iso(new Date(now.getFullYear(),now.getMonth(),0))]}return['','']}
export default function Payroll({data,setData}){
 const employees=(data.employees||[]).filter(e=>e.is_active!==false)
 const [dateStart,setDateStart]=useState(monthStart()),[dateEnd,setDateEnd]=useState(today()),[search,setSearch]=useState(''),[status,setStatus]=useState('Upload any Toast payroll or labor CSV/XLSX to create daily payroll entries.'),[preview,setPreview]=useState([]),[sourceFile,setSourceFile]=useState(''),[selected,setSelected]=useState([])
 const entries=data.payrollEntries||[]
 const filtered=useMemo(()=>entries.filter(row=>{const d=String(row.pay_date||row.payroll_date||'').slice(0,10);if(dateStart&&d<dateStart)return false;if(dateEnd&&d>dateEnd)return false;return !search||normalize(`${row.employee_name} ${row.group_name}`).includes(normalize(search))}).sort((a,b)=>String(b.pay_date||'').localeCompare(String(a.pay_date||''))),[entries,dateStart,dateEnd,search])
 const totals=useMemo(()=>filtered.reduce((a,r)=>{a.hours+=Number(r.hours||0);a.original+=originalTips(r);a.withheld+=Number(r.tip_deduction||r.tips_withheld||0);a.net+=Number(r.tips||0);a.total+=payrollTotal(r);a.names.add(normalize(r.employee_name));return a},{hours:0,original:0,withheld:0,net:0,total:0,names:new Set()}),[filtered])
 const salesWeights=useMemo(()=>Object.fromEntries((data.salesDays||[]).map(r=>[String(r.business_date||r.date||'').slice(0,10),Number(r.net_sales||r.gross_sales||0)])),[data.salesDays])
 async function upload(event){const file=event.target.files?.[0];if(!file)return;try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const period=detectToastLaborPeriod(XLSX,workbook);const rows=parseToastLaborRows(XLSX,workbook,{fileName:file.name,payDate:period.end||today(),tipRate:data.settings?.tipWithholdingRate??3.5,dailySalesWeights:salesWeights});setPreview(rows);setSourceFile(file.name);if(period.start&&period.end){setDateStart(period.start);setDateEnd(period.end)}const diag=laborImportDiagnostics(rows);setStatus(`Ready: ${diag.rows} daily rows for ${diag.employees} employees, ${money(diag.hours)} hours, $${money(diag.totalTips)} original tips, and $${money(diag.netTips)} net tips.`)}catch(error){console.error(error);setStatus(error?.message||'Toast labor import failed.')}finally{event.target.value=''}}
 function commitImport(){if(!preview.length)return setStatus('Upload a Toast file first.');setData(prev=>{const existing=prev.payrollEntries||[];const keys=new Set(existing.map(payrollEntryKey));let added=0;const next=[];for(const source of preview){const employee=employees.find(e=>normalize(e.name)===normalize(displayName(source.employee_name)));const row={id:createId('pay'),employee_id:employee?.id||'',employee_name:employee?.name||displayName(source.employee_name),source:'Toast Payroll V2',source_file:sourceFile,pay_date:source.pay_date,period_start:source.period_start||source.pay_date,period_end:source.period_end||source.pay_date,hours:roundPayroll(source.hours),regular_pay:roundPayroll(source.regular_pay),overtime_pay:roundPayroll(source.overtime_pay),original_tips:roundPayroll(source.total_tips),total_tips:roundPayroll(source.total_tips),tip_deduction:roundPayroll(source.tip_deduction),tips:roundPayroll(source.tips),extra_pay:0,extra_reason:'',payroll_type:employee?.payroll_type||'Check',check_number:employee?.default_check_number||source.check_number||'',allocated:Boolean(source.allocated_from_summary),allocation_method:source.allocation_method||'actual-date',approval_status:'Pending',created_at:new Date().toISOString()};row.total_pay=payrollTotal(row);const k=payrollEntryKey(row);if(keys.has(k))continue;keys.add(k);next.push(row);added++}setStatus(`Imported ${added} new daily payroll entries. ${preview.length-added} duplicate rows were skipped.`);return{...prev,payrollEntries:[...next,...existing],payrollImports:[{id:createId('payimp'),file_name:sourceFile,row_count:added,created_at:new Date().toISOString()},...(prev.payrollImports||[])]}});setPreview([]);setSelected([])}
 function updateEntry(id,field,value){setData(prev=>({...prev,payrollEntries:(prev.payrollEntries||[]).map(row=>{if(row.id!==id)return row;const next={...row,[field]:value};if(field==='original_tips'||field==='tip_deduction'){const original=field==='original_tips'?Number(value||0):originalTips(next);const withheld=field==='tip_deduction'?Number(value||0):Number(next.tip_deduction||0);next.original_tips=roundPayroll(original);next.total_tips=roundPayroll(original);next.tips=roundPayroll(Math.max(0,original-withheld))}next.total_pay=payrollTotal(next);return next})}))}
 function deleteEntry(id){setData(prev=>({...prev,payrollEntries:(prev.payrollEntries||[]).filter(r=>r.id!==id)}));setStatus('Daily payroll entry deleted.')}
 const groups=groupPayrollByEmployee(filtered)
 function toggle(k){setSelected(v=>v.includes(k)?v.filter(x=>x!==k):[...v,k])}
 function buildChecks(){const chosen=groups.filter(g=>selected.includes(g.key));if(!chosen.length)return setStatus('Select at least one employee.');const stamp=new Date().toISOString();setData(prev=>({...prev,payrollEntries:(prev.payrollEntries||[]).map(row=>chosen.some(g=>g.rows.some(r=>r.id===row.id))?{...row,approval_status:'Approved',approved_at:stamp,check_batch_id:`week-${dateStart}-${dateEnd}`} : row)}));setStatus(`Built weekly checks for ${chosen.length} employees while preserving every daily entry.`)}
 function exportCsv(){const headers=['Date','Employee','Hours','Regular Pay','Overtime Pay','Original Tips','Tips Withheld','Net Tips','Extra Pay','Daily Pay','Status'];const rows=filtered.map(r=>[r.pay_date,r.employee_name,money(r.hours),money(r.regular_pay),money(r.overtime_pay),money(originalTips(r)),money(r.tip_deduction),money(r.tips),money(r.extra_pay),money(payrollTotal(r)),r.approval_status||'Pending']);const csv=[headers,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`payroll-daily-${dateStart}-to-${dateEnd}.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className="payroll-rc5-page"><div className="page-head payroll-rc5-head"><div><h1>Payroll</h1><p>Payroll Engine V2 — one permanent entry per employee per business day.</p></div><div className="payroll-rc5-head-actions"><button className="btn secondary" onClick={exportCsv}><Icon name="download"/> Export CSV</button><label className="btn primary payroll-upload-button"><Icon name="upload"/> Upload Toast Labor<input type="file" accept=".csv,.xlsx,.xls" onChange={upload}/></label></div></div>
 <DateControls start={dateStart} end={dateEnd} onStartChange={setDateStart} onEndChange={setDateEnd} onPreset={key=>{const[a,b]=presetRange(key);setDateStart(a);setDateEnd(b)}} onApply={()=>setStatus(`Showing payroll from ${dateStart} through ${dateEnd}.`)} applyLabel="Use Date Range"/>
 <section className="payroll-rc5-card payroll-rc5-filter-card"><div className="payroll-rc5-actions"><label className="payroll-rc5-filter-label"><span>Employee Search</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Type employee name"/></label><button className="btn secondary" onClick={()=>setSearch('')}>Clear</button></div></section><div className="payroll-rc5-status">{status}</div>
 <section className="payroll-rc5-summary"><div><span>Employees</span><strong>{totals.names.size}</strong></div><div><span>Total Hours</span><strong>{money(totals.hours)}</strong></div><div><span>Original Tips</span><strong>${money(totals.original)}</strong></div><div><span>Withheld</span><strong>${money(totals.withheld)}</strong></div><div><span>Net Tips</span><strong>${money(totals.net)}</strong></div><div className="payroll-rc5-final"><span>Total Payroll</span><strong>${money(totals.total)}</strong></div></section>
 {preview.length>0&&<section className="payroll-rc5-card"><div className="payroll-rc5-card-head"><div><h2>Import Preview</h2><p>{sourceFile} created {preview.length} daily entries. Weekly-only summaries are allocated across the detected period and exact totals are retained.</p></div><div className="payroll-rc5-actions"><button className="btn secondary" onClick={()=>setPreview([])}>Cancel</button><button className="btn primary" onClick={commitImport}>Import Daily Entries</button></div></div><div className="payroll-rc5-table-wrap"><table className="payroll-rc5-table history"><thead><tr><th>Date</th><th>Employee</th><th>Hours</th><th>Wages</th><th>Original Tips</th><th>Withheld</th><th>Net Tips</th><th>Allocation</th></tr></thead><tbody>{preview.map((r,i)=><tr key={`${r.employee_name}-${r.pay_date}-${i}`}><td>{r.pay_date}</td><td><b>{displayName(r.employee_name)}</b></td><td>{money(r.hours)}</td><td>${money(Number(r.regular_pay)+Number(r.overtime_pay))}</td><td>${money(r.total_tips)}</td><td>${money(r.tip_deduction)}</td><td>${money(r.tips)}</td><td>{r.allocated_from_summary?(r.allocation_method==='daily-sales'?'Sales weighted':'Even split'):'Actual date'}</td></tr>)}</tbody></table></div></section>}
 <PayrollWeekBuilder rows={filtered} selected={selected} onToggle={toggle} onBuild={buildChecks}/><section className="payroll-rc5-card"><div className="payroll-rc5-card-head"><div><h2>Daily Payroll History</h2><p>Expand an employee to edit or delete individual business days.</p></div></div>{filtered.length?<PayrollDailyGrid rows={filtered} onUpdate={updateEntry} onDelete={deleteEntry}/>:<div className="empty-state">No payroll entries match this range.</div>}</section></div>
}
