import {useMemo,useState} from 'react'
import {ChevronDown,ChevronRight,Search,TrendingDown,TrendingUp,TriangleAlert,WalletCards} from 'lucide-react'
import DateToolbar from '../components/DateToolbar'
import DetailDrawer from '../components/DetailDrawer'
import {appMoney2,useAppData} from '../hooks/useAppData'

export default function PriceIncrease(){
 const {metrics}=useAppData();const [query,setQuery]=useState(''),[impact,setImpact]=useState('All Changes'),[drawer,setDrawer]=useState(null)
 const rows=useMemo(()=>(metrics.priceComparisons||[]).filter(r=>(!query||`${r.item} ${r.vendor}`.toLowerCase().includes(query.toLowerCase()))&&(impact==='All Changes'||(impact==='Increased'&&r.change>0)||(impact==='Decreased'&&r.change<0)||(impact==='Unchanged'&&r.change===0))).sort((a,b)=>String(a.item||'').localeCompare(String(b.item||''),undefined,{numeric:true,sensitivity:'base'})),[metrics.priceComparisons,query,impact])
 const increases=rows.filter(r=>r.change>0).sort((a,b)=>b.change_percent-a.change_percent),decreases=rows.filter(r=>r.change<0),largest=increases[0];const impactTotal=increases.reduce((s,r)=>s+r.change,0);const cards=[['Price Increases',increases.length,'Items above prior cost','red',TrendingUp],['Items Decreased',decreases.length,'Lower current cost','green',TrendingDown],['Largest Increase',largest?`${largest.change_percent.toFixed(1)}%`:'0.0%','Highest item change','orange',TriangleAlert],['Unit Impact',appMoney2(impactTotal),'Sum of normalized changes','purple',WalletCards]]
 return <div className="records-page"><DateToolbar/><section className="records-kpi-grid">{cards.map(([t,v,m,tone,Icon])=><button key={t} className={`records-kpi tone-${tone}`} onClick={()=>setDrawer(t==='Largest Increase'&&largest?{title:`Largest Increase · ${largest.item}`,rows:largest.comparison_rows||largest.history}:t)}><span className="records-kpi-icon"><Icon size={22}/></span><span className="records-kpi-copy"><strong>{t}</strong><b>{v}</b><small>{m}</small></span><ChevronRight size={18}/></button>)}</section><section className="records-workspace card-surface"><header className="records-header"><div><h2>Price Increase</h2><p>Invoice-line price history with lower costs in green and increases in red</p></div></header><div className="records-filterbar"><label className="records-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search item or vendor..."/></label><label className="records-select"><select value={impact} onChange={e=>setImpact(e.target.value)}><option>All Changes</option><option>Decreased</option><option>Increased</option><option>Unchanged</option></select><ChevronDown size={14}/></label></div><div className="records-table-wrap"><table className="records-table aligned-table"><thead><tr><th>Item</th><th>Package</th><th>Basis</th><th>Previous</th><th>Current</th><th>Change</th><th>Vendor</th><th>Best Vendor</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.key} onClick={()=>setDrawer({title:r.item,rows:r.history})}><td>{r.item}</td><td>{r.package_size||'—'}</td><td>{r.comparison_basis==='bottle'?'Per Bottle':r.comparison_basis==='each'?'Per Each':r.comparison_basis==='case'?'Case Cost / Pack Unknown':(r.comparison_basis||r.purchase_unit||'—')}</td><td className="numeric">{appMoney2(r.previous_price)}</td><td className={`numeric ${r.change>0?'price-higher':r.change<0?'price-lower':''}`}>{appMoney2(r.current_price)}</td><td className={`numeric ${r.change>0?'price-higher':r.change<0?'price-lower':''}`}>{r.change>=0?'+':''}{r.change_percent.toFixed(1)}%</td><td>{r.vendor}</td><td>{r.best_vendor}</td></tr>):<tr><td colSpan="8" className="empty-table-cell">At least two invoice prices for the same item are needed.</td></tr>}</tbody></table></div></section><DetailDrawer title={typeof drawer==='string'?drawer:drawer?.title} entries={drawer?.rows} onClose={()=>setDrawer(null)}/></div>
}
