import {useMemo,useState} from 'react'
import {ChevronDown,ChevronRight,Search,Store,Tag,TrendingDown,WalletCards} from 'lucide-react'
import DateToolbar from '../components/DateToolbar'
import DetailDrawer from '../components/DetailDrawer'
import {appMoney2,useAppData} from '../hooks/useAppData'

export default function VendorComparison(){
 const {metrics}=useAppData();const [query,setQuery]=useState(''),[vendorA,setVendorA]=useState('All Vendors'),[vendorB,setVendorB]=useState('All Vendors'),[drawer,setDrawer]=useState(null)
 const history=metrics.priceHistory||[];const vendors=useMemo(()=>[...new Set(history.map(r=>r.vendor).filter(Boolean))].sort(),[history])
 const comparisons=useMemo(()=>{const groups=new Map();history.forEach(row=>{if(query&&!`${row.item} ${row.item_number}`.toLowerCase().includes(query.toLowerCase()))return;if(vendorA!=='All Vendors'&&row.vendor!==vendorA&&vendorB==='All Vendors')return;if(vendorB!=='All Vendors'&&row.vendor!==vendorB&&vendorA==='All Vendors')return;const key=`${row.item_number||row.item}|${row.normalized_unit||row.package_size}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)});return [...groups.values()].map(rows=>{const relevant=rows.filter(r=>(vendorA==='All Vendors'||r.vendor===vendorA)&&(vendorB==='All Vendors'||r.vendor===vendorB));const use=relevant.length?relevant:rows;const best=[...use].sort((a,b)=>(a.unit_cost||a.case_price)-(b.unit_cost||b.case_price))[0];const high=[...use].sort((a,b)=>(b.unit_cost||b.case_price)-(a.unit_cost||a.case_price))[0];return{item:best.item,item_number:best.item_number,package_size:best.package_size,best_vendor:best.vendor,best_price:best.unit_cost||best.case_price,highest_vendor:high.vendor,highest_price:high.unit_cost||high.case_price,savings:Math.max(0,(high.unit_cost||high.case_price)-(best.unit_cost||best.case_price)),rows:use}}).filter(r=>r.rows.length).sort((a,b)=>String(a.item||'').localeCompare(String(b.item||''),undefined,{numeric:true,sensitivity:'base'}))},[history,query,vendorA,vendorB])
 const savings=comparisons.reduce((s,r)=>s+r.savings,0);const cards=[['Compared Items',comparisons.length,'Items with invoice history','blue',Tag],['Best Vendor Matches',comparisons.filter(x=>x.rows.length>1).length,'Multiple vendor options','green',Store],['Potential Savings',appMoney2(savings),'Per normalized purchase unit','purple',TrendingDown],['Invoice Lines',history.length,'Available price records','orange',WalletCards]]
 return <div className="records-page"><DateToolbar/><section className="records-kpi-grid">{cards.map(([t,v,m,tone,Icon])=><button key={t} className={`records-kpi tone-${tone}`} onClick={()=>setDrawer(t)}><span className="records-kpi-icon"><Icon size={22}/></span><span className="records-kpi-copy"><strong>{t}</strong><b>{v}</b><small>{m}</small></span><ChevronRight size={18}/></button>)}</section><section className="records-workspace card-surface"><header className="records-header"><div><h2>Vendor Comparison</h2><p>Compare normalized invoice-line costs across vendors and package sizes</p></div></header><div className="records-filterbar"><label className="records-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search item..."/></label><label className="records-select"><select value={vendorA} onChange={e=>setVendorA(e.target.value)}><option>All Vendors</option>{vendors.map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={14}/></label><label className="records-select"><select value={vendorB} onChange={e=>setVendorB(e.target.value)}><option>All Vendors</option>{vendors.map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={14}/></label></div><div className="records-table-wrap"><table className="records-table aligned-table"><thead><tr><th>Item</th><th>Package</th><th>Best Vendor</th><th>Best Price</th><th>Highest Vendor</th><th>Highest Price</th><th>Savings</th></tr></thead><tbody>{comparisons.length?comparisons.map(r=><tr key={`${r.item}-${r.package_size}`} onClick={()=>setDrawer({title:r.item,rows:r.rows})}><td>{r.item}</td><td>{r.package_size||'—'}</td><td>{r.best_vendor}</td><td className="numeric price-lower">{appMoney2(r.best_price)}</td><td>{r.highest_vendor}</td><td className="numeric price-higher">{appMoney2(r.highest_price)}</td><td className="numeric price-lower">{appMoney2(r.savings)}</td></tr>):<tr><td colSpan="7" className="empty-table-cell">Add invoice line items from two or more vendors to compare pricing.</td></tr>}</tbody></table></div></section><DetailDrawer title={typeof drawer==='string'?drawer:drawer?.title} entries={drawer?.rows} onClose={()=>setDrawer(null)}/></div>
}
