import { useMemo,useState } from 'react'
import { AlertTriangle,Building2,ChevronDown,ChevronLeft,ChevronRight,CircleDollarSign,Filter,Mail,Pencil,Phone,Plus,Search,Store,Trash2,Users,Wrench,Sparkles,Tags } from 'lucide-react'
import DetailDrawer from '../components/DetailDrawer';import Modal from '../components/Modal';import BrandMark from '../components/BrandMark';import useCrudCollection from '../hooks/useCrudCollection';import {lower,searchableText,safeStatus} from '../lib/safe';import {useFeedback} from '../components/AppFeedback'
const seed=[
{id:'v1',name:'US Foods',type:'Inventory Purchase',category:'Food',expenseType:'Inventory',phone:'(205) 555-0148',email:'orders@usfoods.com',spend:12430,status:'Active'},
{id:'v2',name:'Sysco',type:'Inventory Purchase',category:'Food',expenseType:'Inventory',phone:'(205) 555-0182',email:'sales@sysco.com',spend:5835,status:'Active'},
{id:'v3',name:'PFG',type:'Inventory Purchase',category:'Food',expenseType:'Inventory',phone:'(205) 555-0124',email:'service@pfg.com',spend:3234,status:'Active'},
{id:'v4',name:'ABC Board',type:'Inventory Purchase',category:'Liquor',expenseType:'Inventory',phone:'(334) 555-0108',email:'orders@abc.alabama.gov',spend:4120,status:'Active'},
{id:'v5',name:'Cintas',type:'Operating Expense',category:'Supplies',expenseType:'Uniforms & Linen',phone:'(205) 555-0177',email:'support@cintas.com',spend:1875,status:'Inactive'},
{id:'v6',name:'Coca-Cola',type:'Inventory Purchase',category:'Beverage',expenseType:'Inventory',phone:'(205) 555-0110',email:'service@coke.com',spend:2460,status:'Active'},
{id:'v7',name:'Pepsi',type:'Inventory Purchase',category:'Beverage',expenseType:'Inventory',phone:'(205) 555-0190',email:'service@pepsi.com',spend:1940,status:'Active'}]
const baseTypes=['Inventory Purchase','Operating Expense','Maintenance','Service'],baseCategories=['Food','Beer','Wine','Liquor','Beverage','Supplies','Utilities','Maintenance'],baseExpenseTypes=['Inventory','Repairs & Maintenance','Utilities','Uniforms & Linen','Cleaning','Professional Services','Rent','Insurance','Marketing','Other']
const blank={name:'',type:baseTypes[0],category:baseCategories[0],expenseType:baseExpenseTypes[0],phone:'',email:'',spend:0,status:'Active'}
function EditableSelect({label,value,onChange,options,icon:Icon,onAdd}){return <label className="vendor-editable-field"><span>{label}</span><div className="vendor-select-row">{Icon&&<Icon size={15}/>}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select><button type="button" className="inline-add-button" onClick={onAdd}><Plus size={15}/></button></div></label>}
export default function Vendors(){const [rows,crud]=useCrudCollection('restapay-vendors',[]);const {notify}=useFeedback();const [query,setQuery]=useState(''),[typeFilter,setTypeFilter]=useState('All Types'),[categoryFilter,setCategoryFilter]=useState('All Categories'),[drawer,setDrawer]=useState(null),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[duplicate,setDuplicate]=useState(false),[override,setOverride]=useState(false),[form,setForm]=useState(blank);const [types,setTypes]=useState(baseTypes),[categories,setCategories]=useState(baseCategories),[expenseTypes,setExpenseTypes]=useState(baseExpenseTypes)
 const addOption=(kind,list,setList,field)=>{const value=prompt(`Enter new ${kind}`)?.trim();if(value&&!list.some(x=>x.toLowerCase()===value.toLowerCase())){setList([...list,value]);setForm(f=>({...f,[field]:value}));notify(`${kind} added.`)}}
 const safeRows=Array.isArray(rows)?rows.filter(Boolean):[];const filtered=useMemo(()=>safeRows.filter(r=>(!query||searchableText(r).includes(lower(query)))&&(typeFilter==='All Types'||r.type===typeFilter)&&(categoryFilter==='All Categories'||r.category===categoryFilter)),[safeRows,query,typeFilter,categoryFilter])
 const openAdd=()=>{setEditing(null);setForm(blank);setModal(true)};const openEdit=r=>{setEditing(r.id);setForm({...r});setModal(true)}
 const review=()=>{if(!form.name.trim())return notify('Vendor name is required.','error');const dup=safeRows.find(r=>r.id!==editing&&String(r.name||'').replace(/[^a-z0-9]/gi,'').toLowerCase()===form.name.replace(/[^a-z0-9]/gi,'').toLowerCase());if(dup){setModal(false);setDuplicate(true)}else save()}
 const save=()=>{editing?crud.update(editing,form):crud.add(form);notify(editing?'Vendor updated.':'Vendor added.');setModal(false);setDuplicate(false);setOverride(false)}
 const merge=()=>{const existing=safeRows.find(r=>lower(r.name).includes(lower(form.name).split(' ')[0]));if(existing)crud.update(existing.id,{...existing,...form,name:existing.name,spend:Number(existing.spend||0)+Number(form.spend||0)});notify('Vendor merged.');setDuplicate(false)}
 const del=r=>{if(confirm(`Delete ${r.name}?`)){crud.remove(r.id);notify('Vendor deleted.')}}
 const cards=[['Total Vendors',safeRows.length,`${safeRows.filter(r=>safeStatus(r.status)==='Active').length} active vendors`,'blue',Building2],['Inventory Vendors',safeRows.filter(r=>r.type==='Inventory Purchase').length,'Food, beer, liquor & supplies','green',Store],['Expense Vendors',safeRows.filter(r=>r.type!=='Inventory Purchase').length,'Maintenance and operating','orange',CircleDollarSign],['Vendor Spend',`$${safeRows.reduce((s,r)=>s+Number(r.spend||0),0).toLocaleString()}`,'Selected period','purple',Users]]
 return <div className="records-page vendors-page"><section className="records-kpi-grid">{cards.map(([title,value,meta,tone,Icon])=><button key={title} className={`records-kpi tone-${tone}`} onClick={()=>setDrawer(title)}><span className="records-kpi-icon"><Icon size={22}/></span><span><strong>{title}</strong><b>{value}</b><small>{meta}</small></span><ChevronRight size={18}/></button>)}</section><section className="records-workspace card-surface"><header className="records-header"><div><h2>Vendors</h2><p>Manage classifications, duplicates, contacts, and spend</p></div><button className="primary-button" onClick={openAdd}><Plus size={17}/>Add Vendor</button></header><div className="records-filterbar vendor-filterbar"><label className="records-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search vendors..."/></label><label className="records-select"><Filter size={16}/><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option>All Types</option>{types.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><label className="records-select"><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option>All Categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label></div><div className="records-table-wrap"><table className="records-table aligned-table vendors-table"><thead><tr><th>Vendor</th><th>Vendor Type</th><th>Category</th><th>Expense Type</th><th>Phone</th><th>Email</th><th>Spend</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><span className="vendor-name-cell"><BrandMark name={r.name||'Vendor'}/><strong>{r.name||'Unnamed vendor'}</strong></span></td><td>{r.type}</td><td>{r.category}</td><td>{r.expenseType}</td><td><span className="contact-cell"><Phone size={14}/>{r.phone}</span></td><td><span className="contact-cell"><Mail size={14}/>{r.email}</span></td><td className="numeric">${Number(r.spend||0).toLocaleString()}</td><td><button className={`status-badge status-${lower(safeStatus(r.status)).replace(/[^a-z0-9]+/g,'-')}`} onClick={()=>crud.update(r.id,{status:safeStatus(r.status)==='Active'?'Inactive':'Active'})}>{safeStatus(r.status)}</button></td><td><div className="row-actions"><button onClick={()=>openEdit(r)}><Pencil size={15}/></button><button className="danger" onClick={()=>del(r)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div><footer className="records-footer"><span>Showing {filtered.length} of {safeRows.length} vendors</span><div><button disabled><ChevronLeft size={16}/></button><button className="active">1</button><button disabled><ChevronRight size={16}/></button></div></footer></section>
 <Modal open={modal} title={editing?'Edit Vendor':'Add Vendor'} subtitle="Set vendor type, category, and expense classification" onClose={()=>setModal(false)} footer={<><button className="secondary-action" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button" onClick={review}>Review & Save</button></>}><div className="form-grid vendor-form-grid"><label>Vendor Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Vendor company name"/></label><EditableSelect label="Vendor Type" value={form.type} onChange={v=>setForm({...form,type:v})} options={types} icon={Store} onAdd={()=>addOption('vendor type',types,setTypes,'type')}/><EditableSelect label="Category" value={form.category} onChange={v=>setForm({...form,category:v})} options={categories} icon={Tags} onAdd={()=>addOption('category',categories,setCategories,'category')}/><EditableSelect label="Expense Type" value={form.expenseType} onChange={v=>setForm({...form,expenseType:v})} options={expenseTypes} icon={Wrench} onAdd={()=>addOption('expense type',expenseTypes,setExpenseTypes,'expenseType')}/><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Spend<input type="number" value={form.spend} onChange={e=>setForm({...form,spend:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>Inactive</option></select></label></div><div className="vendor-logo-note"><Sparkles size={16}/><span>Known vendors use saved brand marks with a fallback when unavailable.</span></div></Modal>
 <Modal open={duplicate} title="Possible Duplicate Vendor" subtitle="Review similar vendor records before creating a new one" onClose={()=>setDuplicate(false)} footer={<><button className="secondary-action" onClick={()=>setDuplicate(false)}>Cancel</button><button className="secondary-action" onClick={merge}>Merge Records</button><button className="primary-button" disabled={!override} onClick={save}>Override & Create</button></>}><div className="duplicate-alert"><AlertTriangle size={24}/><div><strong>Similar vendor found</strong><span>Choose merge or override.</span></div></div><label className="override-check"><input type="checkbox" checked={override} onChange={e=>setOverride(e.target.checked)}/>I reviewed the duplicate and want to create a separate vendor.</label></Modal><DetailDrawer title={drawer} onClose={()=>setDrawer(null)}/></div>}
