import React from 'react'
import {
  AlertTriangle,
  BarChart3,
  Beer,
  Bell,
  BriefcaseBusiness,
  Building2,
  Calendar,
  CalendarDays,
  Camera,
  Coffee,
  CreditCard,
  DollarSign,
  Download,
  Ellipsis,
  FileSpreadsheet,
  FileText,
  Gift,
  Home,
  Landmark,
  Megaphone,
  Menu,
  ChevronDown,
  ChevronsLeft,
  ChevronsRight,
  Package,
  PieChart,
  PlusCircle,
  ReceiptText,
  RefreshCw,
  Save,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Store,
  TrendingUp,
  Upload,
  User,
  UserCheck,
  Users,
  Utensils,
  WalletCards,
  Wine,
  Wrench,
  X,
  Zap
} from 'lucide-react'

export const iconMap = {
  dashboard: Home,
  sales: BarChart3,
  vendors: Store,
  invoices: FileText,
  employees: Users,
  payroll: WalletCards,
  expenses: CreditCard,
  reports: TrendingUp,
  'price-increase': AlertTriangle,
  'menu-costing': Utensils,
  settings: Settings,
  cart: ShoppingCart,
  store: Store,
  calendar: Calendar,
  dollar: DollarSign,
  gift: Gift,
  users: Users,
  userCheck: UserCheck,
  bag: ShoppingBag,
  card: CreditCard,
  receipt: ReceiptText,
  utensils: Utensils,
  person: User,
  alert: AlertTriangle,
  calendarDays: CalendarDays,
  shield: ShieldCheck,
  upload: Upload,
  plus: PlusCircle,
  bell: Bell,
  business: BriefcaseBusiness,
  building: Building2,
  refresh: RefreshCw,
  search: Search,
  save: Save,
  download: Download,
  camera: Camera,
  beer: Beer,
  beverage: Coffee,
  coffee: Coffee,
  wine: Wine,
  wrench: Wrench,
  package: Package,
  zap: Zap,
  landmark: Landmark,
  megaphone: Megaphone,
  ellipsis: Ellipsis,
  x: X,
  menu: Menu,
  chevronDown: ChevronDown,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  trending: TrendingUp,
  spreadsheet: FileSpreadsheet,
  pie: PieChart
}

export function Icon({ name, size = 20, className = '' }) {
  const Cmp = iconMap[name] || BriefcaseBusiness
  return <Cmp size={size} className={className} />
}
