import { Bell, ChevronDown, LockKeyhole, ShieldCheck, UserRoundCog, Settings, CircleCheck, TriangleAlert } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useFeedback } from './AppFeedback'
import { useAccessControl } from '../lib/accessControl'

const pageMeta={'/dashboard':['Dashboard','Executive overview of your restaurant business'],'/sales':['Sales','Manage Toast imports, daily sales, payment methods, and sales history'],'/food-alcohol-cost':['Food & Alcohol Cost','Track food and alcohol costs by department'],'/invoices':['Invoices','Upload invoices, review totals, and organize vendor bills'],'/vendors':['Vendors','Manage vendors, categories, contacts, and payment terms'],'/vendor-comparison':['Vendor Comparison','Compare invoice item prices, package sizes, and vendor savings'],'/price-increase':['Price Increase','Review vendor item increases and pricing risk'],'/employees':['Employees','Manage employees, roles, pay types, and status'],'/payroll':['Payroll','Process payroll groups, manual payroll, tips, and history'],'/expenses':['Expenses','Track restaurant expenses, payment methods, and categories'],'/reports':['Reports','Generate weekly reports, exports, and business analysis'],'/import-center':['Import Center','Upload and organize restaurant business data'],'/toast-integration':['Toast Integration','Monitor automatic Toast exports and imports'],'/bank-checks':['Bank & Checks','Reconcile bank checks and business documents'],'/settings':['Settings','Manage account and application preferences']}

export default function Topbar(){
 const{pathname}=useLocation(),navigate=useNavigate(),{notify}=useFeedback(),access=useAccessControl()
 const[saveState,setSaveState]=useState('Live'),[menu,setMenu]=useState(false),[alerts,setAlerts]=useState(false)
 const wrapRef=useRef(null)
 const[title,subtitle]=pageMeta[pathname]||['RestaPay','Restaurant business management']
 useEffect(()=>{let timer;const status=(event)=>{const next=event?.detail?.status||'saved';window.clearTimeout(timer);if(next==='saving')setSaveState('Saving…');else if(next==='live')setSaveState('Live');else{setSaveState('Saved');timer=window.setTimeout(()=>setSaveState('Live'),1600)}},failed=()=>{window.clearTimeout(timer);setSaveState('Sync Error')};window.addEventListener('restapay:cloud-status',status);window.addEventListener('restapay:cloud-error',failed);return()=>{window.clearTimeout(timer);window.removeEventListener('restapay:cloud-status',status);window.removeEventListener('restapay:cloud-error',failed)}},[])
 useEffect(()=>{const close=e=>{if(wrapRef.current&&!wrapRef.current.contains(e.target)){setMenu(false);setAlerts(false)}};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[])
 const switchAdmin=async()=>{setMenu(false);const pin=window.prompt('Enter 4–6 digit Admin PIN');if(pin===null)return;try{const ok=await access.unlockAdmin(pin);notify(ok?'Admin mode unlocked.':'Incorrect Admin PIN.',ok?'success':'error')}catch(e){notify(e?.message||'Unable to verify Admin PIN.','error')}}
 const lock=()=>{access.lockAdmin();setMenu(false);navigate('/reports');notify('Admin mode locked. Manager access is active.','success')}
 const toggleAlerts=()=>{setAlerts(v=>!v);setMenu(false)}
 const toggleMenu=()=>{setMenu(v=>!v);setAlerts(false)}
 return <header className="topbar"><div className="topbar-page-title"><h1>{title}</h1><p>{subtitle}</p></div><div className="topbar-actions" ref={wrapRef}><div className={`save-pill ${saveState==='Sync Error'?'save-pill-error':saveState==='Saving…'?'save-pill-saving':''}`}><span className="status-dot"/>{saveState}</div><div className="topbar-popover-wrap"><button className="icon-button notification-button" type="button" aria-label="Notifications" aria-expanded={alerts} onClick={toggleAlerts}><Bell size={19}/>{saveState==='Sync Error'&&<span className="notification-badge">!</span>}</button>{alerts&&<div className="topbar-popover notification-popover"><div className="popover-title">Notifications</div><div className={`notification-item ${saveState==='Sync Error'?'is-error':''}`}>{saveState==='Sync Error'?<TriangleAlert size={17}/>:<CircleCheck size={17}/>}<div><strong>{saveState==='Sync Error'?'Sync needs attention':'System is live'}</strong><small>{saveState==='Sync Error'?'A recent Supabase sync failed. Retry the affected action.':'Supabase synchronization is active. No unread alerts.'}</small></div></div><button onClick={()=>{setAlerts(false);navigate('/settings')}}><Settings size={16}/>Notification Settings</button></div>}</div><div className="profile-switch-wrap"><button type="button" className="profile-switch-button" aria-expanded={menu} onClick={toggleMenu}><div className="avatar">JP</div><div className="user-copy"><strong>Jatin Patel</strong><span>{access.isAdmin?'Admin':access.isManager?'Manager':'View Only'}</span></div><ChevronDown size={16}/></button>{menu&&<div className="profile-switch-menu">{access.isAdmin?<button onClick={lock}><LockKeyhole size={16}/>Lock Admin Mode</button>:<button onClick={switchAdmin}><ShieldCheck size={16}/>Switch to Admin</button>}{access.isAdmin&&<button onClick={()=>{setMenu(false);navigate('/settings')}}><UserRoundCog size={16}/>Users & Security</button>}<button onClick={()=>{access.setCurrentRole('manager');setMenu(false);navigate('/reports')}}><UserRoundCog size={16}/>Switch to Manager</button></div>}</div></div></header>
}
