import { Bell, ChevronDown, LockKeyhole, ShieldCheck, UserRoundCog } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useFeedback } from './AppFeedback'
import { useAccessControl } from '../lib/accessControl'

const pageMeta={'/dashboard':['Dashboard','Executive overview of your restaurant business'],'/sales':['Sales','Manage Toast imports, daily sales, payment methods, and sales history'],'/food-alcohol-cost':['Food & Alcohol Cost','Track food and alcohol costs by department'],'/invoices':['Invoices','Upload invoices, review totals, and organize vendor bills'],'/vendors':['Vendors','Manage vendors, categories, contacts, and payment terms'],'/vendor-comparison':['Vendor Comparison','Compare invoice item prices, package sizes, and vendor savings'],'/price-increase':['Price Increase','Review vendor item increases and pricing risk'],'/employees':['Employees','Manage employees, roles, pay types, and status'],'/payroll':['Payroll','Process payroll groups, manual payroll, tips, and history'],'/expenses':['Expenses','Track restaurant expenses, payment methods, and categories'],'/reports':['Reports','Generate weekly reports, exports, and business analysis'],'/import-center':['Import Center','Upload and organize restaurant business data'],'/toast-integration':['Toast Integration','Monitor automatic Toast exports and imports'],'/bank-checks':['Bank & Checks','Reconcile bank checks and business documents'],'/settings':['Settings','Manage account and application preferences']}
export default function Topbar(){
 const{pathname}=useLocation(),navigate=useNavigate(),{notify}=useFeedback(),access=useAccessControl();const[saveState,setSaveState]=useState('Live'),[menu,setMenu]=useState(false);const[title,subtitle]=pageMeta[pathname]||['RestaPay','Restaurant business management']
 useEffect(()=>{let timer;const status=(event)=>{const next=event?.detail?.status||'saved';window.clearTimeout(timer);if(next==='saving')setSaveState('Saving…');else if(next==='live')setSaveState('Live');else{setSaveState('Saved');timer=window.setTimeout(()=>setSaveState('Live'),1600)}},failed=()=>{window.clearTimeout(timer);setSaveState('Sync Error')};window.addEventListener('restapay:cloud-status',status);window.addEventListener('restapay:cloud-error',failed);return()=>{window.clearTimeout(timer);window.removeEventListener('restapay:cloud-status',status);window.removeEventListener('restapay:cloud-error',failed)}},[])
 const switchAdmin=async()=>{setMenu(false);const pin=window.prompt('Enter 4–6 digit Admin PIN');if(pin===null)return;try{const ok=await access.unlockAdmin(pin);notify(ok?'Admin mode unlocked.':'Incorrect Admin PIN.',ok?'success':'error')}catch(e){notify(e?.message||'Unable to verify Admin PIN.','error')}}
 const lock=()=>{access.lockAdmin();setMenu(false);navigate('/reports');notify('Admin mode locked. Manager access is active.','success')}
 return <header className="topbar"><div className="topbar-page-title"><h1>{title}</h1><p>{subtitle}</p></div><div className="topbar-actions"><div className={`save-pill ${saveState==='Sync Error'?'save-pill-error':saveState==='Saving…'?'save-pill-saving':''}`}><span className="status-dot"/>{saveState}</div><button className="icon-button notification-button" type="button" aria-label="Notifications" onClick={()=>notify(saveState==='Sync Error'?'A recent Supabase sync failed. The affected UI change was rolled back; retry the action.':saveState==='Saving…'?'RESTAPAY is writing the latest change directly to Supabase.':'RESTAPAY is connected to Supabase Realtime. Changes stay synchronized while you move between pages.',saveState==='Sync Error'?'error':'info')}><Bell size={19}/></button><div className="profile-switch-wrap"><button type="button" className="profile-switch-button" onClick={()=>setMenu(v=>!v)}><div className="avatar">JP</div><div className="user-copy"><strong>Jatin Patel</strong><span>{access.isAdmin?'Admin':access.isManager?'Manager':'View Only'}</span></div><ChevronDown size={16}/></button>{menu&&<div className="profile-switch-menu">{access.isAdmin?<button onClick={lock}><LockKeyhole size={16}/>Lock Admin Mode</button>:<button onClick={switchAdmin}><ShieldCheck size={16}/>Switch to Admin</button>}{access.isAdmin&&<button onClick={()=>{setMenu(false);navigate('/settings')}}><UserRoundCog size={16}/>Users & Security</button>}<button onClick={()=>{access.setCurrentRole('manager');setMenu(false);navigate('/reports')}}><UserRoundCog size={16}/>Switch to Manager</button></div>}</div></div></header>
}
