import { Bell, ChevronDown, LockKeyhole, ShieldCheck, UserRoundCog, Settings, CircleCheck, TriangleAlert } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useFeedback } from './AppFeedback'
import { useAccessControl } from '../lib/accessControl.js'
import Modal from './Modal.jsx'

const pageMeta={'/dashboard':['Dashboard','Executive overview of your restaurant business'],'/sales':['Sales','Manage Toast imports, daily sales, payment methods, and sales history'],'/food-alcohol-cost':['Food & Alcohol Cost','Track food and alcohol costs by department'],'/invoices':['Invoices','Upload invoices, review totals, and organize vendor bills'],'/vendors':['Vendors','Manage vendors, categories, contacts, and payment terms'],'/vendor-comparison':['Vendor Comparison','Compare invoice item prices, package sizes, and vendor savings'],'/price-increase':['Price Increase','Review vendor item increases and pricing risk'],'/employees':['Employees','Manage employees, roles, pay types, and status'],'/payroll':['Payroll','Process payroll groups, manual payroll, tips, and history'],'/expenses':['Expenses','Track restaurant expenses, payment methods, and categories'],'/reports':['Reports','Generate weekly reports, exports, and business analysis'],'/import-center':['Import Center','Upload and organize restaurant business data'],'/toast-integration':['Toast Integration','Monitor automatic Toast exports and imports'],'/bank-checks':['Bank & Checks','Reconcile bank checks and business documents'],'/settings':['Settings','Manage account and application preferences']}

export default function Topbar(){
 const{pathname}=useLocation(),navigate=useNavigate(),{notify}=useFeedback(),access=useAccessControl()
 const[saveState,setSaveState]=useState('Live'),[menu,setMenu]=useState(false),[alerts,setAlerts]=useState(false),[pinRole,setPinRole]=useState(null),[pinValue,setPinValue]=useState(''),[pinBusy,setPinBusy]=useState(false)
 const wrapRef=useRef(null)
 const[title,subtitle]=pageMeta[pathname]||['RestaPay','Restaurant business management']
 useEffect(()=>{let timer;const status=(event)=>{const next=event?.detail?.status||'saved';window.clearTimeout(timer);if(next==='saving')setSaveState('Saving…');else if(next==='live')setSaveState('Live');else{setSaveState('Saved');timer=window.setTimeout(()=>setSaveState('Live'),1600)}},failed=()=>{window.clearTimeout(timer);setSaveState('Sync Error')};window.addEventListener('restapay:cloud-status',status);window.addEventListener('restapay:cloud-error',failed);return()=>{window.clearTimeout(timer);window.removeEventListener('restapay:cloud-status',status);window.removeEventListener('restapay:cloud-error',failed)}},[])
 useEffect(()=>{const close=e=>{if(wrapRef.current&&!wrapRef.current.contains(e.target)){setMenu(false);setAlerts(false)}};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[])
 const openPinDialog=role=>{setMenu(false);setAlerts(false);setPinValue('');setPinRole(role)}
 const closePinDialog=()=>{if(pinBusy)return;setPinRole(null);setPinValue('')}
 const submitPin=async()=>{if(!/^\d{4,6}$/.test(pinValue)){notify('PIN must be 4 to 6 digits.','error');return}setPinBusy(true);try{const ok=pinRole==='admin'?await access.unlockAdmin(pinValue):await access.unlockManager(pinValue);if(!ok){notify(`Incorrect ${pinRole==='admin'?'Admin':'Manager'} PIN.`,'error');return}setPinRole(null);setPinValue('');if(pinRole==='manager')navigate('/reports');notify(`${pinRole==='admin'?'Admin mode':'Manager access'} unlocked.`,'success')}catch(e){notify(e?.message||`Unable to verify ${pinRole==='admin'?'Admin':'Manager'} PIN.`,'error')}finally{setPinBusy(false)}}
 const switchAdmin=()=>openPinDialog('admin')
 const switchManager=()=>openPinDialog('manager')
 const toggleAlerts=()=>{setAlerts(v=>!v);setMenu(false)}
 const toggleMenu=()=>{setMenu(v=>!v);setAlerts(false)}
 return <><header className="topbar"><div className="topbar-page-title"><h1>{title}</h1><p>{subtitle}</p></div><div className="topbar-actions" ref={wrapRef}><div className={`save-pill ${saveState==='Sync Error'?'save-pill-error':saveState==='Saving…'?'save-pill-saving':''}`}><span className="status-dot"/>{saveState}</div><div className="topbar-popover-wrap"><button className="icon-button notification-button" type="button" aria-label="Notifications" aria-expanded={alerts} onClick={toggleAlerts}><Bell size={19}/>{saveState==='Sync Error'&&<span className="notification-badge">!</span>}</button>{alerts&&<div className="topbar-popover notification-popover"><div className="popover-title">Notifications</div><div className={`notification-item ${saveState==='Sync Error'?'is-error':''}`}>{saveState==='Sync Error'?<TriangleAlert size={17}/>:<CircleCheck size={17}/>}<div><strong>{saveState==='Sync Error'?'Sync needs attention':'System is live'}</strong><small>{saveState==='Sync Error'?'A recent Supabase sync failed. Retry the affected action.':'Supabase synchronization is active. No unread alerts.'}</small></div></div><button onClick={()=>{setAlerts(false);navigate('/settings')}}><Settings size={16}/>Notification Settings</button></div>}</div><div className="profile-switch-wrap"><button type="button" className="profile-switch-button" aria-expanded={menu} onClick={toggleMenu}><div className="avatar">JP</div><div className="user-copy"><strong>Jatin Patel</strong><span>{access.isAdmin?'Admin':access.isManager?'Manager':'View Only'}</span></div><ChevronDown size={16}/></button>{menu&&<div className="profile-switch-menu">{access.isAdmin?<button onClick={switchManager}><LockKeyhole size={16}/>Switch to Manager</button>:<button onClick={switchAdmin}><ShieldCheck size={16}/>Switch to Admin</button>}{access.isAdmin&&<button onClick={()=>{setMenu(false);navigate('/settings')}}><UserRoundCog size={16}/>Users & Security</button>}{!access.isManager&&<button onClick={switchManager}><UserRoundCog size={16}/>Manager Login</button>}</div>}</div></div></header><Modal open={Boolean(pinRole)} title={pinRole==='admin'?'Administrator Access':'Manager Access'} subtitle={`Enter your ${pinRole==='admin'?'Admin':'Manager'} PIN to switch access`} onClose={closePinDialog} footer={<><button type="button" className="secondary-action" onClick={closePinDialog} disabled={pinBusy}>Cancel</button><button type="button" className="primary-button" onClick={submitPin} disabled={pinBusy}>{pinBusy?'Verifying…':'Unlock'}</button></>}><div className="role-pin-login"><label>{pinRole==='admin'?'Admin':'Manager'} PIN<input autoFocus type="password" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={pinValue} onChange={e=>setPinValue(e.target.value.replace(/\D/g,'').slice(0,6))} onKeyDown={e=>{if(e.key==='Enter')submitPin()}} placeholder="4–6 digits"/></label><p>PINs are verified securely through Supabase and are never displayed in RESTAPAY.</p></div></Modal></>
}
