import {useMemo,useState} from 'react'
import {BookOpen,CalendarDays,ChevronDown,ChevronRight,ExternalLink,Globe2,Search,Store,Tag,TrendingDown,WalletCards} from 'lucide-react'
import DateToolbar from '../components/DateToolbar'
import DetailDrawer from '../components/DetailDrawer'
import {appMoney2,useAppData} from '../hooks/useAppData'
import usePersistentState from '../hooks/usePersistentState'
import {isSupabaseReady,supabase} from '../lib/supabase.js'
import {useFeedback} from '../components/AppFeedback'

const samsSearchUrl=item=>`https://www.samsclub.com/s/${encodeURIComponent(String(item||'').trim())}`
const alpha=(a,b)=>String(a||'').localeCompare(String(b||''),undefined,{numeric:true,sensitivity:'base'})

export default function VendorComparison(){
 const {metrics}=useAppData();const {notify}=useFeedback()
 const [query,setQuery]=useState(''),[vendorA,setVendorA]=useState('All Vendors'),[vendorB,setVendorB]=useState('All Vendors'),[drawer,setDrawer]=useState(null),[checking,setChecking]=useState(''),[view,setView]=useState('comparison')
 const [onlineBenchmarks,setOnlineBenchmarks]=usePersistentState('restapay-online-price-benchmarks',{})
 const [reportSettings,setReportSettings]=usePersistentState('restapay-best-price-report-settings',{minSavings:1,minPercent:1})
 const history=metrics.priceHistory||[]
 const vendors=useMemo(()=>[...new Set(history.map(r=>r.vendor).filter(Boolean))].sort(alpha),[history])
 const comparisons=useMemo(()=>{
   const rows=(metrics.priceComparisons||[]).filter(row=>!query||`${row.item} ${row.item_number||''} ${row.category||''}`.toLowerCase().includes(query.toLowerCase()))
   return rows.filter(row=>{if(vendorA==='All Vendors'&&vendorB==='All Vendors')return true;const names=new Set((row.history||[]).map(r=>r.vendor));return (vendorA==='All Vendors'||names.has(vendorA))&&(vendorB==='All Vendors'||names.has(vendorB))}).sort((a,b)=>alpha(a.item,b.item))
 },[metrics.priceComparisons,query,vendorA,vendorB])
 const priceBook=useMemo(()=>comparisons.flatMap(group=>{const latest=new Map();(group.history||[]).forEach(row=>{const key=String(row.vendor_key||row.vendor||'').toLowerCase();const previous=latest.get(key);if(!previous||String(row.date||'')>String(previous.date||''))latest.set(key,row)});return [...latest.values()].map(row=>({...row,family_item:group.item,best_vendor:group.best_vendor,best_price:group.best_price,match_confidence:group.match_confidence,vendor_count:group.vendor_count}))}).sort((a,b)=>alpha(a.family_item,b.family_item)||alpha(a.vendor,b.vendor)),[comparisons])
 const dailyReport=useMemo(()=>comparisons.filter(row=>{const savings=Number(row.potential_savings||row.savings||0);const current=Number(row.current_price||0);const pct=current?savings/current*100:0;const online=onlineBenchmarks?.[row.key];const onlineSavings=online?Math.max(0,current-Number(online.unit_price||0)):0;return Number(row.vendor_count||0)>1&&(savings>=Number(reportSettings.minSavings||0)||pct>=Number(reportSettings.minPercent||0)||onlineSavings>=Number(reportSettings.minSavings||0))}).sort((a,b)=>Number(b.potential_savings||0)-Number(a.potential_savings||0)),[comparisons,onlineBenchmarks,reportSettings])
 const savings=comparisons.reduce((s,r)=>s+Number(r.potential_savings||r.savings||0),0)
 const bestMatches=comparisons.filter(x=>Number(x.vendor_count||0)>1),savingsMatches=comparisons.filter(x=>Number(x.potential_savings||x.savings||0)>0)
 const cards=[['Compared Items',comparisons.length,'Normalized item histories','blue',Tag,comparisons],['Best Vendor Matches',bestMatches.length,'Exact + AI-similar multi-vendor items','green',Store,bestMatches],['Potential Savings',appMoney2(savings),'For comparable current quantities','purple',TrendingDown,savingsMatches],['Invoice Lines',history.length,'Memorized price records','orange',WalletCards,history]]
 const checkSams=async row=>{setChecking(row.key);try{if(isSupabaseReady){const {data,error}=await supabase.functions.invoke('sams-price-check',{body:{query:row.item,comparison_basis:row.comparison_basis,category:row.category}});if(!error&&data?.price){const entry={provider:"Sam's Club",item:data.item||row.item,price:Number(data.price),unit_price:Number(data.unit_price||data.price),package:data.package||'',url:data.url||samsSearchUrl(row.item),checked_at:new Date().toISOString(),note:data.note||'Public online benchmark; club/member pricing may differ.'};setOnlineBenchmarks(prev=>({...prev,[row.key]:entry}));notify(`Sam's Club benchmark found: ${appMoney2(entry.unit_price)}.`);return}}window.open(samsSearchUrl(row.item),'_blank','noopener,noreferrer');notify("Automatic Sam's Club price lookup was unavailable, so the matching Sam's search was opened.")}catch(error){window.open(samsSearchUrl(row.item),'_blank','noopener,noreferrer');notify(error?.message||"Sam's Club lookup opened in a new tab.",'error')}finally{setChecking('')}}
 return <div className="records-page"><DateToolbar/><section className="records-kpi-grid">{cards.map(([t,v,m,tone,Icon,detailRows])=><button key={t} className={`records-kpi tone-${tone}`} onClick={()=>setDrawer({title:t,rows:detailRows})}><span className="records-kpi-icon"><Icon size={22}/></span><span className="records-kpi-copy"><strong>{t}</strong><b>{v}</b><small>{m}</small></span><ChevronRight size={18}/></button>)}</section>
 <section className="records-workspace card-surface"><header className="records-header"><div><h2>Vendor Price Intelligence</h2><p>RESTAPAY remembers every invoice price, normalizes package quantities, and identifies the cheapest comparable vendor for food, alcohol, kitchen supplies, cleaning and other goods.</p></div></header>
 <div className="vendor-price-tabs"><button className={view==='comparison'?'active':''} onClick={()=>setView('comparison')}><Store size={16}/>Vendor Comparison</button><button className={view==='book'?'active':''} onClick={()=>setView('book')}><BookOpen size={16}/>Price Book</button><button className={view==='daily'?'active':''} onClick={()=>setView('daily')}><CalendarDays size={16}/>Daily Best Price</button></div>
 <div className="records-filterbar"><label className="records-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search item, SKU, category..."/></label><label className="records-select"><select value={vendorA} onChange={e=>setVendorA(e.target.value)}><option>All Vendors</option>{vendors.map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={14}/></label><label className="records-select"><select value={vendorB} onChange={e=>setVendorB(e.target.value)}><option>All Vendors</option>{vendors.map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={14}/></label></div>
 {view==='daily'&&<div className="best-price-settings"><strong>Actionable savings threshold</strong><label>$ minimum <input type="number" min="0" step="0.5" value={reportSettings.minSavings} onChange={e=>setReportSettings({...reportSettings,minSavings:Number(e.target.value)})}/></label><label>% minimum <input type="number" min="0" step="0.5" value={reportSettings.minPercent} onChange={e=>setReportSettings({...reportSettings,minPercent:Number(e.target.value)})}/></label><small>Only comparable multi-vendor items meeting either threshold appear in the daily buying report.</small></div>}
 <div className="records-table-wrap">{view==='book'?<table className="records-table aligned-table vendor-intelligence-table"><thead><tr><th>Item</th><th>Vendor</th><th>Last Price</th><th>Package</th><th>Basis</th><th>Last Seen</th><th>Best Vendor</th><th>Best Price</th><th>Match</th></tr></thead><tbody>{priceBook.length?priceBook.map((r,i)=><tr key={`${r.invoice_id}-${r.id}-${i}`}><td><strong>{r.family_item||r.item}</strong><small>{r.item_number||'No vendor SKU'}</small></td><td>{r.vendor}</td><td className="numeric">{appMoney2(r.unit_cost||r.case_price)}</td><td>{r.package_size||'—'}</td><td>{r.comparison_basis||r.purchase_unit||'unit'}</td><td>{r.date||'—'}</td><td>{r.best_vendor}</td><td className="numeric price-lower">{appMoney2(r.best_price)}</td><td>{r.match_confidence}</td></tr>):<tr><td colSpan="9" className="empty-table-cell">Upload invoices to build the vendor price book.</td></tr>}</tbody></table>:<table className="records-table aligned-table vendor-intelligence-table"><thead><tr><th>Item</th><th>Category</th><th>Basis</th><th>Current Vendor</th><th>Current</th><th>Best Vendor</th><th>Best</th><th>Qty Basis</th><th>Savings</th><th>Match / Online</th></tr></thead><tbody>{(view==='daily'?dailyReport:comparisons).length?(view==='daily'?dailyReport:comparisons).map(r=>{const online=onlineBenchmarks?.[r.key];return <tr key={r.key} onClick={()=>setDrawer({title:r.item,rows:r.history,comparison:r})}><td><strong>{r.item}</strong><small>{r.package_size||'Package not specified'}</small></td><td>{r.category||'Other'}</td><td>{r.comparison_basis||'unit'}</td><td>{r.vendor||'—'}</td><td className="numeric">{appMoney2(r.current_price)}</td><td>{r.best_vendor||'—'}</td><td className="numeric price-lower">{appMoney2(r.best_price)}</td><td className="numeric">{Number(r.comparable_quantity||1).toLocaleString()} {r.comparison_basis||'unit'}</td><td className="numeric price-lower">{appMoney2(r.potential_savings||r.savings||0)}</td><td onClick={e=>e.stopPropagation()}><small className="match-confidence-chip">{r.match_confidence}</small>{online?<a className="online-price-chip" href={online.url} target="_blank" rel="noreferrer"><Globe2 size={14}/>{appMoney2(online.unit_price)}<ExternalLink size={12}/></a>:<button className="secondary-action sams-check-action" disabled={checking===r.key} onClick={()=>checkSams(r)}><Globe2 size={14}/>{checking===r.key?'Checking...':"Check Sam's"}</button>}</td></tr>}):<tr><td colSpan="10" className="empty-table-cell">{view==='daily'?'No actionable vendor savings meet the current thresholds.':'Upload invoices to build price memory. RESTAPAY compares the same normalized quantity before declaring a best vendor.'}</td></tr>}</tbody></table>}</div>
 <p className="vendor-intelligence-note">Price Book uses invoice history as memory. Exact normalized items are preferred; conservative AI-similar matches are labeled so you can review them. Online benchmarks stay separate from vendor invoice history.</p></section>
 <DetailDrawer title={drawer?.title||drawer} entries={drawer?.rows||[]} initialTab={drawer?.rows?.length?'Entries':'Overview'} headerAction={drawer?.comparison?<button className="secondary-action sams-check-action" disabled={checking===drawer.comparison.key} onClick={()=>checkSams(drawer.comparison)}><Globe2 size={14}/>{checking===drawer.comparison.key?'Checking...':"Check Sam's"}</button>:null} onClose={()=>setDrawer(null)}/></div>
}
